# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: root@email.com
  admin_password: password
  domain_name: example.com
  secret_key_base: 4b9ac311b6c88f2fd167be4caf70a233b080687c84a69d5468761200e8bd32b3434fc9d2e284d82174301576255a5c6b11cf492bb545cf914c9d4cdca99aeb1e

test:
  domain_name: example.com 
  secret_key_base: b074ea934aa46649b3d7cf2720f3b9f698f8958d8febc4bdc2a54bdd0393dbfeb0cb43784a29840c8c80daa7b149e6aaa1dbd972d2bc34554ff031b1468dd2ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
